### PR TITLE
Change socket classes to be ip version agnostic.

### PR DESCRIPTION
**Pull request by henrikolsson**
This adds ipv6 support.  Also removed some unused methods.

I've only tried to compile and run this on linux and it seems to work fine with both ipv4 and ipv6. 
If gtkevemon is supposed to work on mac os x and windows it would be great if someone could test this there.

### CODE REVIEW

**Comment by simonfuhrmann** [comment]
This stuff actually compiles under MacOS X. Good job.

**Comment by simonfuhrmann** [comment]
This PR closes #15 and #18.

**Comment by hobarrera** [comment]
Thanks a bunch!
I owe you a 🍺 !

**Comment by henrikolsson** [comment]
No problem, it was an interesting exercise :)

**Pull request merged**
